seml:
    executable: /nfs/homedirs/qian/gr/run_ogbn.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 64G          # memory
        cpus-per-task: 4  # num cores
        time: 0-12:00     # max time, D-HH:MM
        exclude: mdsi-gpu[01,02],gpu[02,15,16,17,18,19,20]
        #        qos: interactive

grid:

    seed:
        type: choice
        options:
            - 123132876
            - 235412535
            - 412341243
            - 457234562
            - 345385123
            - 789023454
            - 380182342
            - 238179046
            - 331245324
            - 349081234

    dataset_name: 
        type: choice
        options:
            - 'products'
        
    inference:
        type: choice
        options: 
            - True
              #             - False
            
    LBMB_val:
        type: choice
        options:
            - True
              #             - False
            
    mode:
        type: choice
        options:
            - 'ppr'

    neighbor_sampling:
        type: choice
        options:
            - 'ppr'
    
    ppr_params.neighbor_topk:
        type: choice
        options:
            - 64
            # - 32

    ppr_params.merge_max_size:
        type: choice
        options:
            - None
    
    ppr_params.primes_per_batch:
        type: choice
        options:
            - 4500
            # - 10000
            
    ppr_params.pushflowthresh:
        type: choice
        options:
            - 5e-4


    batch_order.ordered:
        type: choice
        options:
            - True
#             - False
            
    batch_order.sampled:
        type: choice
        options:
#             - True
            - False


    num_batches:
        type: choice
        options:
            - [16, 8, 8]  # products, gcn, batch size = 1
            
    
    diffusion_param:
        type: choice
        options:
            - 0.25
    
    part_topk:
        type: choice
        options:
            - [1, 1]
    
    micro_batch:
        type: choice
        options:
            - 1
            - 2
    
    batch_size:
        type: choice
        options:
            - 1

    small_trainingset:
        type: choice
        options:
            - 1

GCN:
    fixed:
        graphmodel: 'gcn'
        hidden_channels: 256
        reg: 1e-4
        heads: None
