#seml:
#    executable: /nfs/homedirs/qian/gr/run_ogbn.py
#    name: qcd_gr_exp
#    output_dir: /nfs/homedirs/qian/gr/logs
#    project_root_dir: /nfs/homedirs/qian/gr
#
#slurm:
#    experiments_per_job: 1
#    sbatch_options:
#        gres: gpu:1       # num GPUs
#        mem: 64G          # memory
#        cpus-per-task: 4  # num cores
#        time: 1-00:00     # max time, D-HH:MM
#        exclude: mdsi-gpu[01,02],gpu[15,16,17,18,19,20]
#        #        qos: interactive
#
#grid

    dataset_name: 'products'
        
    inference: True
    LBMB_val: True
    mode: 'rw_sampling'

    neighbor_sampling: 'batch_ppr'


    batch_order:
        ordered: False
        sampled: False


    num_batches: [16, 8, 8]
    diffusion_param: 0.25
    part_topk: [1, 1]
    micro_batch: 1
    batch_size: 1
    small_trainingset: 1
    rw_sampling_params:
        batch_size: [80000, 5000]
        num_steps: 16
        walk_length: 2
        sample_coverage: 100

    graphmodel: 'gcn'
    hidden_channels: 256
    reg: 1.e-4
    heads: null