seml:
    executable: /nfs/homedirs/qian/gr/infer.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 64G          # memory
        cpus-per-task: 4  # num cores
        time: 0-05:00     # max time, D-HH:MM
        exclude: mdsi-gpu[01,02],gpu[15,16,17,18,19,20]
        #        qos: interactive


fixed:
    dataset_name: 'products'
    mode: 'ppr'
    neighbor_sampling: 'ppr'
    diffusion_param: 0.25
    num_batches: [16, 8, 8]
    part_topk: [1, 1]
    
    
grid:

    ppr_params.neighbor_topk:
        type: choice
        options:
            # - 4
            # - 8
            # - 16
            - 32
            - 64

    ppr_params.merge_max_size:
        type: choice
        options:
            - None
            
    ppr_params.primes_per_batch:
        type: choice
        options:
            - 4500
            - 5000
            - 7500
            - 10000
            - 12000
            - 15000
            - 18000
            - 20000
            # - 30000
            # - 40000
            # - 50000
            # - 60000
            # - 72000
            # - 80000
            # - 100000
            # - 120000
            # - 140000
            # - 160000
            # - 180000
            # - 200000
            
    ppr_params.pushflowthresh:
        type: choice
        options:
            - 5e-4

SAGE:
    fixed:
        graphmodel: 'sage'
        hidden_channels: 256
        num_layers: 3
