seml:
    executable: /nfs/homedirs/qian/gr/infer.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 16G          # memory
        cpus-per-task: 4  # num cores
        time: 0-01:00     # max time, D-HH:MM
        exclude: mdsi-gpu[01,02],gpu[02,15,16,17,18,19,20]
        #        qos: interactive


fixed:
    dataset_name: 'reddit'
    mode: 'ppr_shadow'
    neighbor_sampling: 'ppr'
    diffusion_param: 0.25
    num_batches: [400, 200, 200]
    part_topk: [1, 1]
    cache_origin_adj: True
    
    
grid:

    ppr_params.neighbor_topk:
        type: choice
        options:
            # - 2
            # - 4
            # - 8
            # - 16
            - 32

    ppr_params.merge_max_size:
        type: choice
        options:
            - None
            
    ppr_params.primes_per_batch:
        type: choice
        options:
            # - 200
            - 300
            - 500
            # - 800
            # - 1000
            # - 1300
            # - 1500
            # - 1700
            # - 2000
            # - 2500
            # - 3000
            # - 3500
            # - 4000
            # - 4500
            # - 5000
            # - 6000
            # - 7000
            # - 7500
            # - 8000
            # - 8500
            # - 9000
            # - 9500
            # - 10000
            # - 11000
            # - 12000
            # - 15000
    
    ppr_params.pushflowthresh:
        type: choice
        options:
            - 2e-5
        

GAT:
    fixed:
        graphmodel: 'gat'
        heads: 4
        num_layers: 2    # reddit
        hidden_channels: 64     # reddit
