dataset_name: 'reddit'
inference: True
LBMB_val: True
mode: 'n_sampling'
neighbor_sampling: 'batch_ppr'
batch_order:
    ordered: False
    sampled: False
num_batches: [400, 200, 200]
diffusion_param: 0.25
part_topk: [1, 1]
micro_batch: 1
batch_size: 1
small_trainingset: 1
n_sampling_params:
    n_nodes: [20, 20]
    num_batches: [400, 400, 400]

graphmodel: 'gat'
reg: 1.e-4    # reddit
heads: 4
num_layers: 2    # reddit
hidden_channels: 64     # reddit