dataset_name: 'reddit'
diffusion_param: 0.25
inference: True
LBMB_val: True
mode: 'part'
neighbor_sampling: 'batch_ppr'
batch_order:
    ordered: True
    sampled: False
num_batches: [400, 200, 200]
part_topk: [1, 1]
micro_batch: 1
batch_size: 1
small_trainingset: 1

graphmodel: 'gat'
reg: 1.e-4    # reddit
heads: 4
num_layers: 2    # reddit
hidden_channels: 64     # reddit
