dataset_name: 'reddit'
inference: True
LBMB_val: True
mode: 'ppr'
neighbor_sampling: 'ppr'
ppr_params:
    neighbor_topk: 8
    merge_max_size: [10000, 20000, 20000]
    primes_per_batch: 2500
    pushflowthresh: 2.e-5
batch_order:
    ordered: True
    sampled: False
num_batches: [400, 200, 200]
diffusion_param: 0.25
part_topk: [1, 1]
micro_batch: 1
batch_size: 1
small_trainingset: 1

graphmodel: 'gat'
reg: 1.e-4    # reddit
heads: 4
num_layers: 2    # reddit
hidden_channels: 64     # reddit
