seml:
    executable: /nfs/homedirs/qian/gr/run_ogbn.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 32G          # memory
        cpus-per-task: 4  # num cores
        time: 0-06:00     # max time, D-HH:MM
        exclude: mdsi-gpu[01,02],gpu[02,15,16,17,18,19,20]
        #        qos: interactive
        
fixed:
    dataset_name: 'reddit'
    inference: True
    LBMB_val: True
    mode: 'ppr_shadow'
    neighbor_sampling: 'ppr'
    ppr_params:
        neighbor_topk: 6
        merge_max_size: [10000, 20000, 20000]
        primes_per_batch: 2500
        pushflowthresh: 2.e-5
    batch_order:
        ordered: False
        sampled: False
    num_batches: [400, 200, 200]
    diffusion_param: 0.25
    part_topk: [1, 1]
    micro_batch: 1
    batch_size: 1
    small_trainingset: 1
    cache_origin_adj: True
    
    graphmodel: 'gat'
    reg: 1.e-4    # reddit
    heads: 4
    num_layers: 2    # reddit
    hidden_channels: 64     # reddit
        

grid:

    seed:
        type: choice
        options:
            - 123132876
            - 235412535
            - 412341243
            - 457234562
            - 345385123
            - 789023454
            - 380182342
            - 238179046
            - 331245324
            - 349081234
