dataset_name: 'arxiv'
diffusion_param: 0.25
inference: True
LBMB_val: True
mode: 'ppr'
neighbor_sampling: 'ppr'
ppr_params:
    neighbor_topk: 16
    merge_max_size: null
    primes_per_batch: 4000
    pushflowthresh: 2.e-4
batch_order:
    ordered: True
    sampled: False
num_batches: [8, 4, 4]
part_topk: [1, 1]
micro_batch: 1
batch_size: 1
small_trainingset: 1

graphmodel: 'gat'
hidden_channels: 128
reg: 0.
heads: 4
