    dataset_name: 'arxiv'
    inference: True
    LBMB_val: True
    mode: 'rw_sampling'
    ppr_params:
            neighbor_topk: 16
            merge_max_size: null
            primes_per_batch: 4000
            alpha: 0.25
            eps: 2.e-4
    batch_params:
            num_batches: [8, 4, 4]
            part_topk: [ 1, 1 ]
            alpha: 0.25
    rw_sampling_params:
        batch_size: [17500, 10000]
        num_steps: 4
        walk_length: 2
        sample_coverage: 100
    micro_batch: 1
    batch_size: 1
    batch_order: 'rand'
    small_trainingset: 1

    graphmodel: 'gat'
    hidden_channels: 128
    reg: 0.
    heads: 4
    num_layers: 3
