seml:
    executable: /nfs/homedirs/qian/gr/run_ogbn.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 24G          # memory
        cpus-per-task: 4  # num cores
        time: 0-03:00     # max time, D-HH:MM
        exclude: mdsi-gpu[01,02],gpu[15,16,17,18,19,20]
        #        qos: interactive

fixed:
    dataset_name: 'reddit'
    diffusion_param: 0.25
    inference: True
    LBMB_val: True
    mode: 'ppr_shadow'
    neighbor_sampling: 'ppr'
    ppr_params:
        neighbor_topk: 5
        merge_max_size: [80000, 160000, 160000]
        primes_per_batch: 35000
        pushflowthresh: 2.e-5
    batch_order:
        ordered: False
        sampled: False
    num_batches: [8, 4, 4]
    part_topk: [1, 1]
    micro_batch: 1
    batch_size: 1
    small_trainingset: 1
    cache_origin_adj: True
    
    graphmodel: 'gcn'
    hidden_channels: 512
    reg: 0.
    num_layers: 2

grid:

    seed:
        type: choice
        options:
            - 123132876
            - 235412535
            - 412341243
            - 457234562
            - 345385123
            - 789023454
            - 380182342
            - 238179046
            - 331245324
            - 349081234