seml:
    executable: /nfs/homedirs/qian/gr/run_ogbn.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 32G          # memory
        cpus-per-task: 4  # num cores
        time: 0-06:00     # max time, D-HH:MM
        exclude: mdsi-gpu[01,02],gpu[15,16,17,18,19,20]
        #        qos: interactive

grid:

    seed:
        type: choice
        options:
            - 123132876
            - 235412535
            - 412341243
            - 457234562
            - 345385123
            - 789023454
            - 380182342
            - 238179046
            - 331245324
            - 349081234

    dataset_name: 
        type: choice
        options:
            - 'reddit'
        
    inference:
        type: choice
        options: 
            - True
              #             - False
            
    LBMB_val:
        type: choice
        options:
            - True
            # - False
            
    mode:
        type: choice
        options:
            - 'rw_sampling'

    neighbor_sampling:
        type: choice
        options:
            - 'batch_ppr'


    batch_order.ordered:
        type: choice
        options:
            # - True
            - False
            
    batch_order.sampled:
        type: choice
        options:
#             - True
            - False


    num_batches:
        type: choice
        options:
            - [8, 4, 4]
            
    
    diffusion_param:
        type: choice
        options:
            - 0.25
    
    part_topk:
        type: choice
        options:
            - [1, 1]
    
    micro_batch:
        type: choice
        options:
            - 1
    
    batch_size:
        type: choice
        options:
            - 1

    small_trainingset:
        type: choice
        options:
            - 1
#             - 0.001

            
    rw_sampling_params.batch_size:
        type: choice
        options:
            # - [10000, 5000]
            # - [16000, 8000]
            - [20000, 10000]
            # - [22000, 10000]
            # - [30000, 15000]
            
    rw_sampling_params.num_steps:
        type: choice
        options:
            - 8
            
    rw_sampling_params.walk_length:
        type: choice
        options:
            # - 1
            - 2
            # - 3
            
    rw_sampling_params.sample_coverage:
        type: choice
        options:
            - 100

GCN:
    fixed:
        graphmodel: 'gcn'
        hidden_channels: 512
        reg: 0.
        num_layers: 2

