seml:
    executable: /nfs/homedirs/qian/gr/run_ogbn_extra.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 72G          # memory
        cpus-per-task: 4  # num cores
        time: 1-00:00     # max time, D-HH:MM
        exclude: mdsi-gpu[01,02],gpu[02,15,16,17,18,19,20]
        #        qos: interactive

fixed:
    dataset_name: 'products'
    mode: 'ppr_shadow'
    neighbor_sampling: 'ppr'
    ppr_params:
        neighbor_topk: 64
        merge_max_size: null
        primes_per_batch: 130
        pushflowthresh: 5.e-4
    batch_order:
        ordered: False
        sampled: False
    num_batches: [1200, 600, 600]
    diffusion_param: 0.25
    part_topk: [1, 1]
    micro_batch: 1
    batch_size: 1
    small_trainingset: 1
    cache_origin_adj: True
    
    graphmodel: 'gat'
    hidden_channels: 128
    reg: 0.
    heads: 4
        
grid:

    seed:
        type: choice
        options:
            - 123132876
            - 235412535
            - 412341243
            - 457234562
            - 345385123