dataset_name: 'products'
diffusion_param: 0.25
inference: True
LBMB_val: True
mode: 'ppr'
neighbor_sampling: 'ppr'
ppr_params:
    neighbor_topk: 64
    merge_max_size: null
    primes_per_batch: 4500
    pushflowthresh: 5.e-4
batch_order:
    ordered: True
    sampled: False
num_batches: [16, 8, 8]
part_topk: [1, 1]
micro_batch: 1
batch_size: 1
small_trainingset: 1

graphmodel: 'sage'
hidden_channels: 256
reg: 0.
num_layers: 3
