seml:
    executable: /nfs/homedirs/qian/gr/infer.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 24G          # memory
        cpus-per-task: 4  # num cores
        time: 0-02:00     # max time, D-HH:MM
        exclude: gpu15,gpu16,gpu17,gpu18,gpu19
        #        qos: interactive
        
fixed:
    dataset_name: 'reddit'
    mode: 'n_sampling'
    neighbor_sampling: 'batch_ppr'
    diffusion_param: 0.25
    num_batches: [8, 4, 4]
    part_topk: [1, 1]

grid:

    n_sampling_params.n_nodes:
        type: choice
        options:
            # - [10, 10, 10]
            # - [20, 20, 20]
            # - [50, 50, 50]
            - [100, 100, 100]
      
    n_sampling_params.num_batches:
        type: choice
        options:
            # - [1, 1, 1]
            # - [2, 2, 1]
            # - [4, 4, 1]
            - [8, 8, 1]
    
SAGE:
    fixed:
        graphmodel: 'sage'
        hidden_channels: 256
        num_layers: 3
