seml:
    executable: /nfs/homedirs/qian/gr/infer.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 32G          # memory
        cpus-per-task: 4  # num cores
        time: 0-01:00     # max time, D-HH:MM
        exclude: mdsi-gpu[01,02],gpu[15,16,17,18,19,20]
        #        qos: interactive

fixed:
    dataset_name: 'reddit'
    mode: 'part'
    neighbor_sampling: 'batch_ppr'
    diffusion_param: 0.25

    # part_topk: [1, 0.6]
    # num_batches: [1, 2, 2]
    
    # part_topk: [1, 1]
    # num_batches: [1, 4, 4]
    
    # part_topk: [1, 2]
    # num_batches: [1, 8, 8]
    
    part_topk: [1, 4]
    num_batches: [1, 16, 16]

SAGE:
    fixed:
        graphmodel: 'sage'
        hidden_channels: 256
        num_layers: 3
