dataset_name: 'arxiv'
inference: True
LBMB_val: True
mode: 'rw_sampling'
neighbor_sampling: 'batch_ppr'
batch_order:
    ordered: False
    sampled: False
num_batches: [4, 2, 2]
diffusion_param: 0.25
part_topk: [1, 1]
micro_batch: 1
batch_size: 1
small_trainingset: 1
rw_sampling_params:
    batch_size: [24000, 12000]
    num_steps: 4
    walk_length: 2
    sample_coverage: 100

graphmodel: 'sage'
hidden_channels: 256
reg: 0.
num_layers: 3