dataset_name: 'products'
inference: True
LBMB_val: True
mode: 'n_sampling'
neighbor_sampling: 'batch_ppr'
batch_order:
    ordered: False
    sampled: False
num_batches: [1200, 600, 600]
diffusion_param: 0.25
part_topk: [1, 1]
micro_batch: 1
batch_size: 1
small_trainingset: 1
n_sampling_params:
    n_nodes: [15, 10, 10]
    num_batches: [1200, 180, 9600]

graphmodel: 'gat'
hidden_channels: 128
reg: 0.
heads: 4