dataset_name: 'products'
inference: True
LBMB_val: True
mode: 'ppr'
neighbor_sampling: 'ppr'
ppr_params:
    neighbor_topk: 64
    merge_max_size: null
    primes_per_batch: 130
    pushflowthresh: 5.e-4
batch_order:
    ordered: True
    sampled: False
num_batches: [1200, 600, 600]  # prod, gat, batch size = 1
diffusion_param: 0.25
part_topk: [1, 1]
micro_batch: 1
batch_size: 1
small_trainingset: 1

graphmodel: 'gat'
hidden_channels: 128
reg: 0.
heads: 4
