dataset_name: 'products'
inference: True
LBMB_val: True
mode: 'rw_sampling'
neighbor_sampling: 'batch_ppr'
batch_order:
    ordered: False
    sampled: False
num_batches: [1200, 600, 600]
diffusion_param: 0.25
part_topk: [1, 1]
micro_batch: 1
batch_size: 1
small_trainingset: 1
rw_sampling_params:
    batch_size: [12000, 100]
    num_steps: 1200
    walk_length: 2
    sample_coverage: 100

graphmodel: 'gat'
hidden_channels: 128
reg: 0.
heads: 4