dataset_name: 'reddit'
inference: True
LBMB_val: True
mode: 'n_sampling'
neighbor_sampling: 'batch_ppr'
batch_order:
    ordered: False
    sampled: False
num_batches: [8, 4, 4]
diffusion_param: 0.25
part_topk: [1, 1]
micro_batch: 1
batch_size: 1
small_trainingset: 1
n_sampling_params:
    n_nodes: [5, 5, 5]
    num_batches: [8, 4, 4]

graphmodel: 'sage'
hidden_channels: 256
reg: 0.
num_layers: 3
        
    