seml:
    executable: /nfs/homedirs/qian/gr/run_ogbn.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 24G          # memory
        cpus-per-task: 4  # num cores
        time: 0-12:00     # max time, D-HH:MM
        exclude: mdsi-gpu[01,02],gpu[15,16,17,18,19,20]
        #        qos: interactive

grid:

    seed:
        type: choice
        options:
            - 123132876
            - 235412535
            - 412341243
            - 457234562
            - 345385123
            - 789023454
            - 380182342
            - 238179046
            - 331245324
            - 349081234

    dataset_name: 
        type: choice
        options:
            - 'reddit'
        
    inference:
        type: choice
        options: 
            - True
              #             - False
            
    LBMB_val:
        type: choice
        options:
            - True
              #             - False
            
    mode:
        type: choice
        options:
            - 'n_sampling'

    neighbor_sampling:
        type: choice
        options:
            - 'batch_ppr'

    batch_order.ordered:
        type: choice
        options:
            # - True
            - False
            
    batch_order.sampled:
        type: choice
        options:
#             - True
            - False


    num_batches:
        type: choice
        options:
            - [8, 4, 4]
            
    
    diffusion_param:
        type: choice
        options:
            - 0.25
    
    part_topk:
        type: choice
        options:
            - [1, 1]
    
    micro_batch:
        type: choice
        options:
            - 1
            - 2
    
    batch_size:
        type: choice
        options:
            - 1

    small_trainingset:
        type: choice
        options:
            - 1
#             - 0.001


    n_sampling_params.n_nodes:
        type: choice
        options:
            - [5, 5, 5]
            # - [5, 6, 5]
            # - [6, 5, 5]
            # - [6, 6, 5]
                    
    n_sampling_params.num_batches:
        type: choice
        options:
            - [8, 4, 4]

SAGE:
    fixed:
        graphmodel: 'sage'
        hidden_channels: 256
        reg: 0.
        num_layers: 3
        
    