dataset_name: 'reddit'
diffusion_param: 0.25
inference: True
LBMB_val: True
mode: 'part'
neighbor_sampling: 'batch_ppr'
batch_order:
    ordered: True
    sampled: False
num_batches: [8, 4, 4]
part_topk: [1, 1]
micro_batch: 1
batch_size: 1
small_trainingset: 1

graphmodel: 'sage'
hidden_channels: 256
reg: 0.
num_layers: 3
