dataset_name: 'reddit'
diffusion_param: 0.25
inference: True
LBMB_val: True
mode: 'ppr_shadow'
neighbor_sampling: 'ppr'
ppr_params:
    neighbor_topk: 5
    merge_max_size: [80000, 160000, 160000]
    primes_per_batch: 35000
    pushflowthresh: 2.e-5
batch_order:
    ordered: False
    sampled: False
num_batches: [8, 4, 4]
part_topk: [1, 1]
micro_batch: 1
batch_size: 1
small_trainingset: 1
cache_origin_adj: True

graphmodel: 'sage'
hidden_channels: 256
reg: 0.
num_layers: 3
