seml:
    executable: /nfs/homedirs/qian/gr/run_ogbn_extra.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 72G          # memory
        cpus-per-task: 4  # num cores
        time: 0-05:00     # max time, D-HH:MM
        exclude: gpu15,gpu16,gpu17,gpu18,gpu19,gpu08,gpu11
        #        qos: interactive

grid:

    dataset_name: 
        type: choice
        options:
            - 'products'
            
    mode:
        type: choice
        options:
            - 'ppr'
            
    neighbor_sampling:
        type: choice
        options:
            - 'ppr'
    
    ppr_params.neighbor_topk:
        type: choice
        options:
            - 64

    ppr_params.merge_max_size:
        type: choice
        options:
            - None
            
    ppr_params.primes_per_batch:
        type: choice
        options:
            - 4500
            # - 10000
            
    ppr_params.pushflowthresh:
        type: choice
        options:
            - 5e-4


    batch_order.ordered:
        type: choice
        options:
#             - True
            - False
            
    batch_order.sampled:
        type: choice
        options:
#             - True
            - False


    num_batches:
        type: choice
        options:
            - [16, 8, 8]
            
    
    diffusion_param:
        type: choice
        options:
            - 0.05
    
    part_topk:
        type: choice
        options:
            - [1, 1]
    
    micro_batch:
        type: choice
        options:
            - 1
    
    batch_size:
        type: choice
        options:
            - 1

    small_trainingset:
        type: choice
        options:
            - 1
#             - 0.001



SAGE:
    fixed:
        graphmodel: 'sage'
        hidden_channels: 256
        reg: 0.
        num_layers: 3