seml:
    executable: /nfs/homedirs/qian/gr/run_ogbn_extra.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 32G          # memory
        cpus-per-task: 4  # num cores
        time: 0-03:00     # max time, D-HH:MM
        exclude: gpu15,gpu16,gpu17,gpu18,gpu19
        #        qos: interactive

grid:

    dataset_name: 
        type: choice
        options:
            - 'products'
            
    mode:
        type: choice
        options:
            - 'ladies'

    neighbor_sampling:
        type: choice
        options:
            # - 'ppr'
            - 'batch_ppr'

    batch_order.ordered:
        type: choice
        options:
#             - True
            - False
            
    batch_order.sampled:
        type: choice
        options:
#             - True
            - False


    num_batches:
        type: choice
        options:
            - [16, 8, 8]  # products, gcn, batch size = 1
    
    diffusion_param:
        type: choice
        options:
            - 0.25
    
    part_topk:
        type: choice
        options:
            - [1, 1]
    
    micro_batch:
        type: choice
        options:
            - 1
    
    batch_size:
        type: choice
        options:
            - 1

    small_trainingset:
        type: choice
        options:
            - 1
#             - 0.001

    ladies_params.sample_size:
        type: choice
        options:
            - [204085, 306128, 306128]  #prod, gcn

GCN:
    fixed:
        graphmodel: 'gcn'
        hidden_channels: 256
        reg: 1e-4
