seml:
    executable: /nfs/homedirs/qian/gr/infer_full.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 16G          # memory
        cpus-per-task: 4  # num cores
        time: 0-03:00     # max time, D-HH:MM
        exclude: gpu15,gpu16,gpu17,gpu18,gpu19
        #        qos: interactive

grid:
    
    dataset_name: 
        type: choice
        options:
            - 'reddit'

    num_batches:
        type: choice
        options:
            - [8, 4, 4]
    
    graphmodel:
        type: choice
        options:
            - 'sage'
    
    num_layers:
        type: choice
        options:
            - 3
            
    hidden_channels:
        type: choice
        options:
            - 256
