dataset_name: 'papers100M'
inference: True
mode: 'ppr'
neighbor_sampling: 'ppr'
ladies_params:
    sample_size: [433827, 867654, 867654]
    n_nodes: [10, 10, 8]
n_sampling_params:
    num_batches: [256, 32, 48]
ppr_params:
    neighbor_topk: 96
    merge_max_size: null
    primes_per_batch: 5000
    pushflowthresh: 2.e-5
batch_order:
    ordered: True
    sampled: False
num_batches: [256, 32, 48]
diffusion_param: 0.05
part_topk: [1, 1]
micro_batch: 1
batch_size: 1
small_trainingset: 1
full_infer: False
clear_cache: True

graphmodel: 'gcn'
hidden_channels: 256
reg: 1.e-4
num_layers: 3