seml:
    executable: /nfs/homedirs/qian/gr/infer.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 32G          # memory
        cpus-per-task: 4  # num cores
        time: 0-01:00     # max time, D-HH:MM
        exclude: mdsi-gpu[01,02],gpu[15,16,17,18,19,20]
        #        qos: interactive

fixed:
    dataset_name: 'reddit'
    mode: 'part'
    neighbor_sampling: 'batch_ppr'
    diffusion_param: 0.25
    
    part_topk: [1, 2]
    num_batches: [1, 8, 8]

GCN:
    fixed:
        graphmodel: 'gcn'
        hidden_channels: 512
        num_layers: 2
