seml:
    executable: /nfs/homedirs/qian/gr/run_ogbn_extra.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 8G          # memory
        cpus-per-task: 4  # num cores
        time: 0-01:00     # max time, D-HH:MM
        exclude: gpu15,gpu16,gpu17,gpu18,gpu19,gpu08
        #        qos: interactive

fixed:

    dataset_name:  'arxiv'
    mode: 'ppr'
    neighbor_sampling: 'ppr'
    batch_order.ordered: False
    batch_order.sampled: False
    ppr_params.neighbor_topk: 16
    ppr_params.merge_max_size: None
    ppr_params.primes_per_batch: 4000
    ppr_params.pushflowthresh: 2e-4
    num_batches: [8, 4, 4]
    diffusion_param: 0.05
    part_topk: [1, 1]
    micro_batch: 1
    batch_size: 1
    small_trainingset: 1
    cache_sub_adj: True
    cache_origin_adj: False
            
GAT:
    fixed:
        graphmodel: 'gat'
        hidden_channels: 128
        reg: 0.
        heads: 4