seml:
    executable: /nfs/homedirs/qian/gr/run_ogbn_extra.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 16G          # memory
        cpus-per-task: 4  # num cores
        time: 0-01:00     # max time, D-HH:MM
        exclude: gpu15,gpu16,gpu17,gpu18,gpu19
        #        qos: interactive

fixed:

    dataset_name:  'reddit'
            
    mode: 'n_sampling'

    neighbor_sampling: 'batch_ppr'

    batch_order.ordered: False
            
    batch_order.sampled: False


    num_batches: [400, 200, 200]
            
    
    diffusion_param: 0.25
    
    part_topk: [1, 1]
    
    micro_batch: 1
    
    batch_size: 1

    small_trainingset: 1

    cache_sub_adj: True
    cache_origin_adj: False

    n_sampling_params.n_nodes: [20, 20]
                    
    n_sampling_params.num_batches: [400, 200, 200]

GAT:
    fixed:
        graphmodel: 'gat'
        reg: 0.
        heads: 4
        num_layers: 2    # reddit
        hidden_channels: 64     # reddit