seml:
    executable: /nfs/homedirs/qian/gr/infer.py
    name: qcd_gr_exp
    output_dir: /nfs/homedirs/qian/gr/logs
    project_root_dir: /nfs/homedirs/qian/gr

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 12G          # memory
        cpus-per-task: 4  # num cores
        time: 0-01:00     # max time, D-HH:MM
        exclude: mdsi-gpu[01,02],gpu[15,16,17,18,19,20]
        #        qos: interactive


fixed:
    dataset_name: 'arxiv'
    mode: 'rand'
    neighbor_sampling: 'ppr'
    diffusion_param: 0.25
    num_batches: [4, 2, 2]
    part_topk: [1, 1]
    cache_sub_adj: True
    cache_origin_adj: True
    
    
grid:

    ppr_params.neighbor_topk:
        type: choice
        options:
            - 4
            - 8
            - 16
            - 32
            - 64

    ppr_params.merge_max_size:
        type: choice
        options:
            - None

SAGE:
    fixed:
        graphmodel: 'sage'
        hidden_channels: 256
        num_layers: 3
